@baseUrl = http://localhost:3000
@auth_token = {{authenticate.response.body.acess_token}}

# @name create_account
POST {{baseUrl}}/users/accounts/create
Content-Type: application/json

{
    "name" : "Teste HTTP Client",
    "email" : "test-client@http.com",
    "password" : "123456"
}

###

# @name authenticate
POST {{baseUrl}}/auth
Content-Type: application/json

{
    "email" : "test-client@http.com",
    "password" : "123456"
}

###

# @name create_question
POST {{baseUrl}}/questions/create
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{

}